"use client";

import type { Project } from "@/lib/types";

type DashboardExportData = {
  chartData: Record<string, string | number>[];
  analysis: {
    peakExact: number;
    overCapacityPeriods: number;
    riskLevel: string;
    peaks: { label: string; crew: number; rounded: number; contributors: { id: string; name: string; value: number }[] }[];
  };
  totalHours: number;
  thisWeekPeak: number;
  projectMix: { id: string; name: string; totalHours: number }[];
};

const GOLD: [number, number, number] = [199, 177, 87];
const GOLD_FILL: [number, number, number] = [253, 249, 225];
const NAVY: [number, number, number] = [15, 25, 38];
const MUTED: [number, number, number] = [100, 116, 139];
const RED: [number, number, number] = [220, 38, 38];

function fmt(v: number, d = 2): string {
  return v.toLocaleString("en-CA", { minimumFractionDigits: d, maximumFractionDigits: d });
}

export async function exportDashboardPDF(
  data: DashboardExportData,
  selectedProjects: Project[],
  capacity: number
) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  const PW = doc.internal.pageSize.getWidth();   // 297
  const PH = doc.internal.pageSize.getHeight();  // 210
  const M = 12;
  const CW = PW - 2 * M;
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-CA", { year: "numeric", month: "short", day: "numeric" });
  const dateShort = `${String(now.getDate()).padStart(2, "0")}-${String(now.getMonth() + 1).padStart(2, "0")}-${now.getFullYear()}`;

  const drawFooter = (pageNum: number, total: number) => {
    doc.setFillColor(248, 249, 250);
    doc.rect(0, PH - 8, PW, 8, "F");
    doc.setFontSize(6.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(
      `Generated by Groupe Piché app  ·  ${dateStr}  ·  Page ${pageNum} of ${total}`,
      PW / 2, PH - 2.5, { align: "center" }
    );
  };

  // ── PAGE 1 ─────────────────────────────────────────────────────────────────

  // Gold header bar
  doc.setFillColor(...GOLD);
  doc.rect(0, 0, PW, 13, "F");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("GROUPE PICHÉ", M, 8.5);

  const projectTitle =
    selectedProjects.length === 1
      ? selectedProjects[0].name.toUpperCase()
      : "COMPANY WORKFORCE";
  doc.setFontSize(14);
  doc.text(`${projectTitle} — Manpower Curve`, PW / 2, 8.5, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(dateShort, PW - M, 8.5, { align: "right" });

  let y = 16;

  // ── KPI STRIP ──────────────────────────────────────────────────────────────
  const activeCount = selectedProjects.filter((p) => p.status !== "Planning").length;
  const kpis = [
    { label: "ACTIVE PROJECTS",    value: String(activeCount) },
    { label: "TOTAL LABOUR HRS",   value: fmt(data.totalHours, 0) },
    { label: "PEAK CREW NEEDED",   value: fmt(data.analysis.peakExact, 2) },
    { label: "CREW THIS WEEK",     value: fmt(data.thisWeekPeak, 2) },
    { label: "OVER-CAPACITY",      value: String(data.analysis.overCapacityPeriods) },
    { label: "MAX CREW REQUIRED",  value: String(Math.ceil(data.analysis.peakExact)) },
    { label: "RISK LEVEL",         value: data.analysis.riskLevel ?? "—" }
  ];

  const KPI_W = CW / kpis.length;
  const KPI_H = 20;

  kpis.forEach((kpi, i) => {
    const kx = M + i * KPI_W;
    doc.setFillColor(252, 252, 255);
    doc.setDrawColor(220, 224, 230);
    doc.setLineWidth(0.15);
    doc.rect(kx, y, KPI_W - 0.4, KPI_H, "FD");
    doc.setFontSize(5.5);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...GOLD);
    doc.text(kpi.label, kx + KPI_W / 2, y + 5.5, { align: "center" });
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text(kpi.value, kx + KPI_W / 2, y + 15, { align: "center" });
  });

  y += KPI_H + 5;

  // ── CHART ──────────────────────────────────────────────────────────────────
  const chartData = data.chartData;
  const n = chartData.length;

  // Determine value key
  const getVal = (row: Record<string, string | number>): number => {
    if (selectedProjects.length === 1) {
      const v = row[selectedProjects[0].name];
      if (typeof v === "number") return v;
    }
    const td = row["Total Demand"];
    if (typeof td === "number") return td;
    for (const k of Object.keys(row)) {
      if (k !== "period" && k !== "sort" && typeof row[k] === "number") return row[k] as number;
    }
    return 0;
  };

  const CHART_LEFT_PAD = 16; // room for y-axis labels
  const CHART_X = M + CHART_LEFT_PAD;
  const CHART_W = CW - CHART_LEFT_PAD - 8; // 8mm right margin for cap label
  const CHART_H = 65;
  const CHART_Y = y;
  const CHART_BASE = CHART_Y + CHART_H;

  let yMax = 1;
  chartData.forEach((row) => { const v = getVal(row); if (v > yMax) yMax = v; });
  if (capacity > 0 && capacity > yMax) yMax = capacity;
  yMax *= 1.12;

  const xPos = (i: number) => n <= 1 ? CHART_X + CHART_W / 2 : CHART_X + (i / (n - 1)) * CHART_W;
  const yPos = (v: number) => CHART_BASE - (v / yMax) * CHART_H;

  // Chart white background + border
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(210, 215, 220);
  doc.setLineWidth(0.2);
  doc.rect(CHART_X, CHART_Y, CHART_W, CHART_H, "FD");

  // Horizontal grid lines + y-axis labels
  const STEPS = 5;
  for (let i = 0; i <= STEPS; i++) {
    const val = (i / STEPS) * yMax;
    const yp = CHART_BASE - (i / STEPS) * CHART_H;
    doc.setDrawColor(232, 235, 238);
    doc.setLineWidth(0.1);
    doc.line(CHART_X, yp, CHART_X + CHART_W, yp);
    doc.setFontSize(5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(Math.round(val).toString(), CHART_X - 1.5, yp + 1, { align: "right" });
  }

  // Y-axis label
  doc.setFontSize(6);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...NAVY);
  doc.text("WEEKLY CREW", M + 4, CHART_Y + CHART_H / 2, { angle: 90, align: "center" });

  // Area fill (gold, drawn as vertical strips for trapezoid approximation)
  if (n >= 2) {
    for (let i = 0; i < n - 1; i++) {
      const x1 = xPos(i);
      const x2 = xPos(i + 1);
      const y1 = yPos(getVal(chartData[i]));
      const y2 = yPos(getVal(chartData[i + 1]));
      const topY = Math.min(y1, y2);
      doc.setFillColor(...GOLD_FILL);
      doc.setDrawColor(...GOLD_FILL);
      doc.rect(x1, topY, x2 - x1, CHART_BASE - topY, "F");
    }
    // Re-draw border so it wasn't eaten by fills
    doc.setDrawColor(210, 215, 220);
    doc.setLineWidth(0.2);
    doc.rect(CHART_X, CHART_Y, CHART_W, CHART_H, "D");
  }

  // Re-draw grid lines on top of fill
  for (let i = 0; i <= STEPS; i++) {
    const yp = CHART_BASE - (i / STEPS) * CHART_H;
    doc.setDrawColor(220, 224, 228);
    doc.setLineWidth(0.1);
    doc.line(CHART_X, yp, CHART_X + CHART_W, yp);
  }

  // Capacity line (dashed red)
  if (capacity > 0) {
    const capY = yPos(capacity);
    doc.setDrawColor(...RED);
    doc.setLineWidth(0.55);
    doc.setLineDashPattern([2, 1.2], 0);
    doc.line(CHART_X, capY, CHART_X + CHART_W, capY);
    doc.setLineDashPattern([], 0);
    doc.setFontSize(6);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...RED);
    doc.text(`Cap: ${capacity}`, CHART_X + CHART_W + 1.5, capY + 1.5);
  }

  // Line connecting data points (gold)
  if (n >= 2) {
    doc.setDrawColor(...GOLD);
    doc.setLineWidth(0.9);
    for (let i = 0; i < n - 1; i++) {
      doc.line(
        xPos(i), Math.max(CHART_Y, Math.min(CHART_BASE, yPos(getVal(chartData[i])))),
        xPos(i + 1), Math.max(CHART_Y, Math.min(CHART_BASE, yPos(getVal(chartData[i + 1]))))
      );
    }
  }

  // X-axis period labels
  const labelStep = n <= 20 ? 1 : Math.max(1, Math.floor(n / 16));
  chartData.forEach((row, i) => {
    if (i % labelStep === 0 || i === n - 1) {
      doc.setFontSize(4.8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...MUTED);
      doc.text(String(row.period || ""), xPos(i), CHART_BASE + 3.8, { align: "center" });
    }
  });

  // X-axis label
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...NAVY);
  doc.text("WEEK", CHART_X + CHART_W / 2, CHART_BASE + 7.5, { align: "center" });

  // Data point dots + value labels on each point
  const showAllLabels = n <= 52;
  const labelEvery = showAllLabels ? 1 : Math.max(1, Math.ceil(n / 40));

  chartData.forEach((row, i) => {
    const v = getVal(row);
    const px = xPos(i);
    const py = Math.max(CHART_Y + 1, Math.min(CHART_BASE - 1, yPos(v)));
    const overCap = capacity > 0 && v > capacity;

    // Dot
    if (overCap) {
      doc.setFillColor(...RED);
      doc.circle(px, py, 1.1, "F");
    } else {
      doc.setFillColor(...NAVY);
      doc.circle(px, py, 0.8, "F");
    }

    // Value label above the dot
    if (i % labelEvery === 0) {
      doc.setFontSize(4.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...(overCap ? RED : NAVY));
      doc.text(fmt(v, 2), px, py - 1.8, { align: "center" });
    }
  });

  y = CHART_BASE + 11;

  // ── DATA TABLE ─────────────────────────────────────────────────────────────
  if (n > 0 && y + 13 < PH - 10) {
    const colW = Math.min((CW) / n, 18);
    const tableW = colW * n;
    const tableX = M + (CW - tableW) / 2;
    const ROW = 5.5;

    // Header row
    chartData.forEach((row, i) => {
      const cx = tableX + i * colW;
      doc.setFillColor(...GOLD);
      doc.setDrawColor(175, 155, 55);
      doc.setLineWidth(0.1);
      doc.rect(cx, y, colW, ROW, "FD");
      doc.setFontSize(4.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      const lbl = String(row.period || "").slice(0, 9);
      doc.text(lbl, cx + colW / 2, y + ROW - 1.2, { align: "center" });
    });

    // Values row
    chartData.forEach((row, i) => {
      const cx = tableX + i * colW;
      const v = getVal(row);
      const overCap = capacity > 0 && v > capacity;
      const alt = i % 2 === 0;
      doc.setFillColor(alt ? 248 : 255, alt ? 249 : 255, alt ? 250 : 255);
      doc.setDrawColor(210, 215, 220);
      doc.setLineWidth(0.1);
      doc.rect(cx, y + ROW, colW, ROW, "FD");
      doc.setFontSize(4.5);
      doc.setFont("helvetica", overCap ? "bold" : "normal");
      doc.setTextColor(overCap ? RED[0] : 30, overCap ? RED[1] : 30, 30);
      doc.text(fmt(v, 2), cx + colW / 2, y + ROW + ROW - 1.2, { align: "center" });
    });
  }

  drawFooter(1, 1);
  doc.save(`manpower-curve-${dateShort}.pdf`);
}
